### ISSUE TITLE
Ojo con esto

### ISSUE THREAD

**Issue by GianottiG** [Agus17LA/LabV#3]
https://github.com/Agus17LA/LabV/blob/24782d194d1526f0479243758a1e9eaaea807c13/TpCerveceria/src/models/BeerProducer.java#L22

Tene cuidado aca para ambos casos, fijate que cada consumidor y cada productor de esta manera trabaja contra una cerveceria distinta, y van a estar agregando o sacando cervezas pero a diferentes, la idea es que todos los hilos esten trabajando con los mismos recursos

**Comment by Agus17LA** [comment]
La clase "BeerHouse" tiene un atributo llamado "stock" que es static, así se solucionaría?

**Comment by Agus17LA** [comment]
> https://github.com/Agus17LA/LabV/blob/24782d194d1526f0479243758a1e9eaaea807c13/TpCerveceria/src/models/BeerProducer.java#L22
> 
> Tene cuidado aca para ambos casos, fijate que cada consumidor y cada productor de esta manera trabaja contra una cerveceria distinta, y van a estar agregando o sacando cervezas pero a diferentes, la idea es que todos los hilos esten trabajando con los mismos recursos

La clase "BeerHouse" tiene un atributo llamado "stock" que es static, así se solucionaría?

**Comment by GianottiG** [comment]
el stock va a ser el mismo para todos, fijo, pero cada objeto es nuevo cuando haces el new BeerHouse
te va a quedar:
 para el Hilo 1  una nueva Beeerhouse con stock 100
 para el Hilo 2  una nueva Beeerhouse con stock 100
y asi con todos y van a sumarle o restarle a esa instancia de cerveceria, el new tendria que estar afuera y todos los hilos tener la misma cerveceria

**Comment by Agus17LA** [comment]
Joya, ahí lo arreglé
